## For each buffer:
- for the preceeding year, (overwinter_start) find when the last hotspot was detected.
- for the proceeding year, (overwinter_1) find when the first hotspot was detected.
- for the end of processing year, (overwinter_1_end), find when the last hotspot was detected.
- for the proceeding year, (overwinter_2), find when the first hotspot was detected
- overwinter_start = 2023
- overwinter_1 = 2024
- overwinter_1_end = 2024 fall
- overwinter_2 = 2025

## Using the dates and location of each hotspot, calculate:
- time between two hotspots
- distances between two hotspots
- distance from buffer edge
- distance from previous years fire boundary
- when lightning was detected +/- 72 hrs
- when snow melted for each buffer.
- when snow onset for each buffer.


## Files:

**buffers:** geometery = original perimeter, buffer_wkt = buffer geom. Both in wkt must to transformed to geodataframe when read in.
- overwinter_start: data/processed_wildfire_buffers/perims_2023_clipped_buffers.parquet
- overwinter_1 : data/processed_wildfire_buffers/perims_2024_clipped_buffers.parquet
- overwinter_2 : data/processed_wildfire_buffers/perims_2025_clipped_buffers.parquet

**hotspots:**
= 2023-2024



## workflow:
Look at 2024 hotspots, and 2023 buffer. If a hotspot occurs in a 2023 buffer, find the day of the buffer. Return a dataframe multiple rows for each and hotspot overlap, have column for hotspot geometry or ID, and date. Keep all columns from perimeter.

In [13]:
import sys
sys.path.insert(0, "../src")

import geopandas as gpd
import pandas as pd
from find_hotspots_in_buffer import find_hotspots_in_buffers

## Step 1: Find hotspots in preceding-year buffers

For each hotspot year, spatially join to the buffer of the preceding year's fire perimeters.
- **2024 hotspots × 2023 buffers** → potential overwinter candidates from 2023 fires
- **2025 hotspots × 2024 buffers** → potential overwinter candidates from 2024 fires

Each result includes:
- `fire_perimeter_id` — which preceding-year perimeter the hotspot fell within
- `hotspot_year` — year of the hotspot
- `distance_to_perimeter` — Euclidean distance (m) from hotspot to original perimeter edge
- `distance_from_last_hotspot` — distance (m) from last hotspot observed *inside* the perimeter in the preceding year

In [14]:
# 2024 hotspots in 2023 buffers (overwinter_start → overwinter_1)
hotspots_in_buffers_2024 = find_hotspots_in_buffers(hotspot_year=2024, save=True)
hotspots_in_buffers_2024.head()

Loading 2024 hotspots and 2023 buffers...
Running spatial join (hotspots within buffers)...
Calculating distance_to_perimeter...
Finding last hotspot per perimeter in 2023...
Calculating distance_from_last_hotspot...
  23163 hotspots found in 2023 buffers

/Users/jgoldman/Documents/postdoc/overwintering/notebooks/../src/find_hotspots_in_buffer.py:171: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  return joined
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Field ACQ_DATE created as String field, though DateTime requested.
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'fire_perimeter_id' to 'fire_perim'
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'hotspot_year' to 'hotspot_ye'
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'distance_to_perimeter' to 'distance_t'
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'last_hotspot_date_in_perimeter' to 'last_hotsp'
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Field last_hotsp created as String field, though DateTime requested.
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'distance_from_last_hotspot' to 'distance_f'
  ogr_write(

  saved hotspots_in_buffers_2024.shp and hotspots_in_buffers_2024.geojson

,LATITUDE,LONGITUDE,BRIGHTNESS,SCAN,TRACK,ACQ_DATE,ACQ_TIME,SATELLITE,INSTRUMENT,CONFIDENCE,...,DAYNIGHT,TYPE,source,year,geometry,fire_perimeter_id,hotspot_year,distance_to_perimeter,last_hotspot_date_in_perimeter,distance_from_last_hotspot
12,56.58211,-121.25147,331.50,0.34,0.56,2024-05-24,1930,N20,VIIRS,n,...,D,0.0,J1V-C2,2024,POINT (1290994.654 1297571.909),20,2024,0.000000,2023-10-13,148.563578
13,56.58226,-121.24985,297.66,0.35,0.57,2024-05-25,0920,N20,VIIRS,n,...,N,0.0,J1V-C2,2024,POINT (1291092.658 1297595.269),20,2024,0.000000,2023-10-13,209.763645
14,56.58244,-121.25571,304.08,0.35,0.57,2024-05-25,0920,N20,VIIRS,n,...,N,0.0,J1V-C2,2024,POINT (1290732.746 1297591.227),20,2024,0.000000,2023-10-13,200.141273
15,56.43418,-121.21347,335.31,0.48,0.48,2024-01-28,1948,N20,VIIRS,n,...,D,0.0,J1V-C2,2024,POINT (1294435.019 1281259.959),8,2024,173.999708,NaT,NaN
16,56.56920,-121.15707,334.22,0.40,0.37,2024-04-18,2045,N20,VIIRS,n,...,D,0.0,J1V-C2,2024,POINT (1296869.109 1296526.68),20,2024,0.000000,2023-10-13,6075.635666

In [15]:
# 2025 hotspots in 2024 buffers (overwinter_1_end → overwinter_2)
hotspots_in_buffers_2025 = find_hotspots_in_buffers(hotspot_year=2025, save=True)
hotspots_in_buffers_2025.head()

Loading 2025 hotspots and 2024 buffers...
Running spatial join (hotspots within buffers)...
Calculating distance_to_perimeter...
Finding last hotspot per perimeter in 2024...
Calculating distance_from_last_hotspot...
  2072 hotspots found in 2024 buffers
  saved hotspots_in_buffers_2025.shp and hotspots_in_buffers_2025.geojson

/Users/jgoldman/Documents/postdoc/overwintering/notebooks/../src/find_hotspots_in_buffer.py:171: UserWarning: Column names longer than 10 characters will be truncated when saved to ESRI Shapefile.
  return joined
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Field ACQ_DATE created as String field, though DateTime requested.
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'fire_perimeter_id' to 'fire_perim'
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'hotspot_year' to 'hotspot_ye'
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'distance_to_perimeter' to 'distance_t'
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'last_hotspot_date_in_perimeter' to 'last_hotsp'
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Field last_hotsp created as String field, though DateTime requested.
  ogr_write(
/Users/jgoldman/Documents/postdoc/overwintering/.venv/lib/python3.14/site-packages/pyogrio/raw.py:733: RuntimeWarning: Normalized/laundered field name: 'distance_from_last_hotspot' to 'distance_f'
  ogr_write(

,LATITUDE,LONGITUDE,BRIGHTNESS,SCAN,TRACK,ACQ_DATE,ACQ_TIME,SATELLITE,INSTRUMENT,CONFIDENCE,...,DAYNIGHT,TYPE,source,year,geometry,fire_perimeter_id,hotspot_year,distance_to_perimeter,last_hotspot_date_in_perimeter,distance_from_last_hotspot
239,58.32583,-120.24101,297.06,0.38,0.36,2025-05-30,1020,N20,VIIRS,n,...,N,0.0,J1V-C2,2025,POINT (1336991.977 1495958.321),27,2025,234.938317,2024-06-01,25923.128879
240,58.32632,-120.24477,296.21,0.45,0.47,2025-05-11,0936,N20,VIIRS,n,...,N,0.0,J1V-C2,2025,POINT (1336768.009 1495994.839),27,2025,356.756321,2024-06-01,25909.475182
241,58.32650,-120.23809,305.82,0.42,0.38,2025-05-29,1039,N20,VIIRS,n,...,N,0.0,J1V-C2,2025,POINT (1337156.397 1496046.623),27,2025,251.305382,2024-06-01,26046.435375
242,58.32904,-120.23920,305.12,0.38,0.36,2025-05-30,1020,N20,VIIRS,n,...,N,0.0,J1V-C2,2025,POINT (1337068.586 1496323.383),27,2025,540.274116,2024-06-01,26296.073394
243,58.32977,-120.23574,311.63,0.42,0.38,2025-05-29,1039,N20,VIIRS,n,...,N,0.0,J1V-C2,2025,POINT (1337263.971 1496420.922),27,2025,552.474129,2024-06-01,26435.439608

## Step 2: Summary — hotspot counts per preceding-year perimeter

In [ ]:
def summarise(gdf, hotspot_year):
    fire_year = int(hotspot_year) - 1

    # Ensure date columns are datetime before any arithmetic
    gdf = gdf.copy()
    gdf["ACQ_DATE"] = pd.to_datetime(gdf["ACQ_DATE"])
    gdf["last_hotspot_date_in_perimeter"] = pd.to_datetime(gdf["last_hotspot_date_in_perimeter"])

    first_detection = (
        gdf.sort_values("ACQ_DATE")
        .groupby("fire_perimeter_id")
        .first()
        .reset_index()
        [["fire_perimeter_id", "ACQ_DATE", "distance_to_perimeter",
          "distance_from_last_hotspot", "last_hotspot_date_in_perimeter"]]
        .rename(columns={
            "ACQ_DATE": f"first_hotspot_{hotspot_year}",
            "distance_to_perimeter": "dist_to_perimeter_at_first",
            "distance_from_last_hotspot": "dist_from_last_hotspot",
            "last_hotspot_date_in_perimeter": f"last_hotspot_{fire_year}",
        })
    )

    counts = (
        gdf.groupby("fire_perimeter_id")
        .agg(
            n_hotspots_in_buffer=("ACQ_DATE", "count"),
            last_hotspot_in_buffer=("ACQ_DATE", "max"),
        )
        .reset_index()
    )

    summary = first_detection.merge(counts, on="fire_perimeter_id")

    summary["days_since_last_detection"] = (
        summary[f"first_hotspot_{hotspot_year}"] - summary[f"last_hotspot_{fire_year}"]
    ).dt.days

    summary = summary[[
        "fire_perimeter_id",
        f"last_hotspot_{fire_year}",
        f"first_hotspot_{hotspot_year}",
        "days_since_last_detection",
        "dist_to_perimeter_at_first",
        "dist_from_last_hotspot",
        "n_hotspots_in_buffer",
        "last_hotspot_in_buffer",
    ]]

    n_perims = len(summary)
    n_no_prev = summary[f"last_hotspot_{fire_year}"].isna().sum()
    print(f"{fire_year} fires → {hotspot_year} buffer hotspots")
    print(f"  {len(gdf)} hotspot matches across {n_perims} perimeters")
    print(f"  {n_no_prev} perimeters had no {fire_year} hotspot inside the original boundary")
    return summary

summary_2024 = summarise(hotspots_in_buffers_2024, hotspot_year=2024)
summary_2024

In [12]:
summary_2025 = summarise(hotspots_in_buffers_2025, "2025 hotspots in 2024 buffers")
summary_2025

2025 hotspots in 2024 buffers: 2072 hotspot matches across 9 perimeters

,fire_perimeter_id,n_hotspots,first_hotspot,last_hotspot,mean_dist_to_perimeter,mean_dist_from_last
0,8,1,2025-04-04,2025-04-04,61.988451,NaN
1,13,11,2025-04-05,2025-05-20,236.221953,556.756386
2,27,30,2025-05-02,2025-05-30,590.044506,26386.228440
3,28,6,2025-05-03,2025-05-17,152.690640,6114.883431
4,29,1,2025-01-27,2025-01-27,332.042364,834.131436
5,35,5,2025-05-09,2025-05-12,732.994181,NaN
6,40,340,2025-05-27,2025-06-01,151.132851,13537.791988
7,45,1651,2025-04-16,2025-06-01,156.383319,125023.242780
8,54,27,2025-05-31,2025-06-01,102.467606,1427.395920